### ISSUE TITLE
Save to environment?

### ISSUE THREAD

**Issue by ruraldev** [XeroAPI/xoauth#4]
Should the following command save the tokens to the environment?
xoauth token xero --refresh --env
It doesn't seem to work for me

**Comment by JoshBarr** [comment]
Hey @ruraldev, 

Unfortunately, when a process sets environment variables, it only applies to itself and any children - a process isn't allowed to modify global environment directly. The solution is to eval the output as follows: 

```shell
eval "$(xoauth token xero --refresh --env)"
```

I noticed we had a typo in the docs (missing `$` and quotes around the subshell). I have amended the docs to reflect correct usage.
